[package]
name = "noted-auth"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
noted-core = { workspace = true }
oxide-auth = "0.6"
governor = "0.10"
macaroon = "0.3"
rand = "0.10"
redb = "4"
scrypt = { version = "0.12", features = ["phc", "getrandom"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
tracing = { workspace = true }
url = "2"

[dev-dependencies]
humantime = { workspace = true }
tempfile = { workspace = true }
