pub mod authclient;
pub mod backend;
pub mod cli;
pub mod config;
pub mod credentials;
pub mod error;
pub mod front_matter;
pub mod http;
pub mod httpurl;
pub mod mcp;
pub mod newtype;
pub mod note;
pub mod notes;
pub mod oauth;
pub mod password;
pub(crate) mod picker;
pub mod scope;
pub mod search;
pub mod serve;
pub mod tasks;
#[allow(dead_code)]
pub(crate) mod text_editor;
pub mod tools;
pub mod types;
pub mod util;

pub use error::{NotedError, Result};
pub use mcp::{McpContext, context};
pub use note::{BinaryNote, Etag, Note, RelPath, TextNote};
pub use notes::{LogNote, Notes};
pub use tasks::{TaskNote, Tasks};
