[package]
name = "noted-picker"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "picker"

[dependencies]
nucleo-matcher = "0.3"
