mod areas;
mod backend;
mod policy;
mod policyargs;
mod root;

pub mod authority;
pub mod authorization;
pub mod error;
pub mod front_matter;
pub mod httpurl;
pub mod newtype;
pub mod note;
pub mod path;
pub mod search;
pub mod store;
pub mod tasks;
pub mod tools;
pub mod types;
pub mod util;

pub use authority::Authority;
pub use authorization::{Authorization, Bearer};
pub use backend::{AuthorizedBackend, Backend, BackendArgs, ToolCall, ToolListing, Transport};
pub use error::{NotedError, Result};
pub use httpurl::HttpUrl;
pub use note::{BinaryNote, Etag, LogNote, Note, TextNote, Trashed};
pub use path::Path;
pub use policyargs::PolicyArgs;
pub use root::NotedRoot;
pub use store::NotedDir;
pub use tasks::TaskNote;
